// Generated by scripts/examples-index.js — do not edit by hand.
window.EXAMPLES = {
  "Basics": [
    "Load an image",
    "Load images from atlas",
    "Pivots and Anchors"
  ],
  "Sprites": [
    "Alpha and Blending",
    "Cache As Bitmap",
    "Cache As Bitmap Dynamic",
    "Clipping Rectangle",
    "Color",
    "Containers",
    "Content Scale",
    "Parent Alpha and Blending",
    "Scale",
    "Skew",
    "Slice 9 Grid",
    "Snap To Pixels",
    "Spine",
    "Sprite Animation",
    "Texture Repeat"
  ],
  "Text": [
    "Advanced Text Metrics",
    "Anchors",
    "Bitmap Font",
    "Displaying text",
    "Having fun",
    "Load Google Font",
    "Load local font",
    "Load multiple fonts",
    "Multiline",
    "Rich Text",
    "Text and stroke alpha",
    "Text Shadow",
    "Text Stroke"
  ],
  "Input": [
    "Circle shaped hitbox",
    "Drag Sprite",
    "Keyboard",
    "Layers",
    "Pointer Messages"
  ],
  "Game Object": [
    "Add Remove Child",
    "Draw Bounds",
    "Static Objects"
  ],
  "Tweening": [
    "Basic",
    "Chain",
    "Events",
    "Interpolation",
    "Loop",
    "Pause",
    "Repeat",
    "Reuse"
  ],
  "Particles": [
    "Bubbles",
    "Click burst",
    "Custom Modifiers",
    "Presimulate",
    "Rain",
    "Random Texture",
    "Sort Order",
    "Space",
    "Trails",
    "Tweening Emitter",
    "Vector Field"
  ],
  "Graphics": [
    "Basic Shapes",
    "Bezier",
    "Having fun"
  ],
  "Messages": [
    "Sending and Receiving"
  ],
  "Arcade Physics": [
    "Basic Usage",
    "Colliders",
    "CollisionEvents",
    "Containers",
    "Mario",
    "Rotated",
    "WorldBounds"
  ],
  "Asset Manager": [
    "Loading assets"
  ],
  "Audio": [
    "Channel Effects",
    "Play sound",
    "Sound Atlas",
    "Spatial Sound",
    "Waveform"
  ],
  "Camera": [
    "Camera"
  ],
  "Coroutines": [
    "Wait Fot it"
  ],
  "Drivers": [
    "Render Texture",
    "Skip Unchanged Frames"
  ],
  "Stage": [
    "Bounds",
    "Fixed Scale Mode",
    "Letterbox",
    "No Scale Mode",
    "Normal Scale Mode",
    "Orientations",
    "Orientations Lock",
    "Scene Manager"
  ],
  "Timers": [
    "Interval",
    "Pause",
    "Reset and reusing"
  ],
  "Vector Graphics": [
    "Vector As a Sprite"
  ]
};
