/**
 * Generates the examples index:
 *
 *   examples/manifest.js          sidebar data for examples/index.html
 *   examples/README.md            category overview
 *   examples/<Category>/README.md per-category example listing
 *
 * Replaces the gulp `<!-- INJECT -->` step and the `@icons` template macro the
 * documentation site used, neither of which works on GitHub. Everything here is
 * derived from the files on disk, so the listings cannot drift out of date.
 *
 * The READMEs are generated. Edit this script, not them.
 *
 * Usage: npm run examples:index
 */

'use strict';

const fs = require('fs');
const path = require('path');

const EXAMPLES_DIR = path.resolve(__dirname, '..', 'examples');
const MANIFEST_FILE = path.join(EXAMPLES_DIR, 'manifest.js');
const SITE_URL = 'https://massiveheights.github.io/Black';
const EXAMPLES_URL = `${SITE_URL}/examples/`;

// Files and directories prefixed with `!` are internal or unfinished.
const INTERNAL_PREFIX = '!';

// Optional blurb shown under a category heading.
const DESCRIPTIONS = {
  'Basics': 'Start here: loading images, atlases, pivots and anchors.'
};

const GENERATED_NOTE = '<!-- Generated by scripts/examples-index.js. Do not edit by hand. -->';

function isPublic(name) {
  return !name.startsWith(INTERNAL_PREFIX);
}

function readOrder() {
  try {
    const config = JSON.parse(fs.readFileSync(path.join(EXAMPLES_DIR, 'config.json'), 'utf8'));
    return Array.isArray(config.order) ? config.order : [];
  } catch (e) {
    return [];
  }
}

function collect() {
  const groups = {};

  for (const entry of fs.readdirSync(EXAMPLES_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory() || !isPublic(entry.name))
      continue;

    const examples = fs.readdirSync(path.join(EXAMPLES_DIR, entry.name))
      .filter(f => f.endsWith('.js') && isPublic(f))
      .map(f => f.slice(0, -3))
      .sort((a, b) => a.localeCompare(b));

    if (examples.length > 0)
      groups[entry.name] = examples;
  }

  return groups;
}

function sortGroups(groups) {
  const order = readOrder();
  const names = Object.keys(groups).sort((a, b) => {
    const ia = order.indexOf(a);
    const ib = order.indexOf(b);

    if (ia !== -1 && ib !== -1) return ia - ib;
    if (ia !== -1) return -1;
    if (ib !== -1) return 1;

    return a.localeCompare(b);
  });

  const sorted = {};
  for (const name of names)
    sorted[name] = groups[name];

  return sorted;
}

function demoURL(group, example) {
  return `${EXAMPLES_URL}?group=${encodeURIComponent(group)}&example=${encodeURIComponent(example + '.js')}`;
}

function writeRootReadme(groups, total) {
  const lines = [
    GENERATED_NOTE,
    '',
    '# Examples',
    '',
    `${total} runnable examples across ${Object.keys(groups).length} categories.`,
    '',
    `Open the [live examples browser](${EXAMPLES_URL}) to run any of them in place, or`,
    'browse a category below for its source.',
    '',
    'To run them locally, serve the repository root (`npx serve .`) and open',
    '`/examples/` — the examples load assets over HTTP and will not work from `file://`.',
    '',
    '| Category | Examples |',
    '| --- | --- |'
  ];

  for (const group in groups)
    lines.push(`| [${group}](${encodeURI(group)}) | ${groups[group].length} |`);

  lines.push('');
  fs.writeFileSync(path.join(EXAMPLES_DIR, 'README.md'), lines.join('\n'));
}

function writeGroupReadme(group, examples) {
  const lines = [
    GENERATED_NOTE,
    '',
    `# ${group}`,
    ''
  ];

  if (DESCRIPTIONS[group]) {
    lines.push(DESCRIPTIONS[group], '');
  }

  lines.push(
    `${examples.length} example${examples.length === 1 ? '' : 's'}. ` +
    'Follow a name to run it in the browser, or open its source alongside.',
    '',
    '| Example | Source |',
    '| --- | --- |'
  );

  for (const example of examples)
    lines.push(`| [${example}](${demoURL(group, example)}) | [${example}.js](${encodeURI(example)}.js) |`);

  lines.push('', `[← All categories](../README.md)`, '');
  fs.writeFileSync(path.join(EXAMPLES_DIR, group, 'README.md'), lines.join('\n'));
}

const groups = sortGroups(collect());
const total = Object.values(groups).reduce((n, list) => n + list.length, 0);

const banner = '// Generated by scripts/examples-index.js — do not edit by hand.\n';
fs.writeFileSync(MANIFEST_FILE, banner + 'window.EXAMPLES = ' + JSON.stringify(groups, null, 2) + ';\n');

writeRootReadme(groups, total);
for (const group in groups)
  writeGroupReadme(group, groups[group]);

console.log(`Wrote manifest.js, README.md and ${Object.keys(groups).length} category READMEs: ` +
  `${total} examples across ${Object.keys(groups).length} categories.`);
